package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"cs2a/internal/cs2"
)

// Whitelist manages the mm-cs2whitelist file (cfg/cs2whitelist/whitelist.txt)
// with one normalized SteamID64 per line. It is a plain file the metamod
// plugin reads at connect time; cs2a is the single writer.
type Whitelist struct {
	cfg Config
}

// NewWhitelist builds the whitelist service.
func NewWhitelist(cfg Config) *Whitelist { return &Whitelist{cfg: cfg} }

// Path is the whitelist file location.
func (w *Whitelist) Path() string {
	return filepath.Join(w.cfg.CFGDir(), "cs2whitelist", "whitelist.txt")
}

// EnabledCvar is the convar cs2a manages in server.cfg to toggle the plugin.
const EnabledCvar = "mm_whitelist_enable"

// Apply normalizes, dedupes and writes the whitelist file atomically.
// Enabling/disabling enforcement is exposed separately via Enable.
func (w *Whitelist) Apply(entries []string) ([]string, error) {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		id, err := cs2.NormalizeSteamID(e)
		if err != nil {
			return nil, fmt.Errorf("whitelist: %q: %w", e, err)
		}
		if _, dup := seen[id]; dup {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	sort.Strings(out)

	var b strings.Builder
	b.WriteString("# cs2a managed whitelist (one SteamID64 per line)\n")
	b.WriteString("# generated by cs2a agent — do not edit while the panel manages it\n")
	for _, id := range out {
		b.WriteString(id + "\n")
	}
	if err := os.MkdirAll(filepath.Dir(w.Path()), 0o755); err != nil {
		return nil, err
	}
	if err := atomicWrite(w.Path(), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}
	return out, nil
}

// Read parses the current whitelist file (ids only, comments skipped).
func (w *Whitelist) Read() ([]string, error) {
	raw, err := os.ReadFile(w.Path())
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "//") {
			continue
		}
		out = append(out, line)
	}
	return out, nil
}
