package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"cs2a/internal/cs2"
)

// Whitelist manages the mm-cs2whitelist plugin's data files:
//
//	cfg/cs2whitelist/whitelist.txt  — one normalized SteamID64 per line
//	cfg/cs2whitelist/core.cfg       — KeyValues config with the on/off switch
//
// The switch lives in core.cfg's "Enable" key, which the plugin reads once in
// AllPluginsLoaded and copies into its `mm_whitelist_enable` cvar. core.cfg is
// therefore the persistent setting, and the cvar is the live one: writing the
// file alone leaves the running server on its old value until the plugin is
// loaded again (a server restart), which is why SetEnabled is paired with an
// RCON push of the cvar. cs2a is the single writer of both files.
type Whitelist struct {
	cfg Config
}

// NewWhitelist builds the whitelist service.
func NewWhitelist(cfg Config) *Whitelist { return &Whitelist{cfg: cfg} }

// Path is the whitelist file location.
func (w *Whitelist) Path() string {
	return filepath.Join(w.cfg.CFGDir(), "cs2whitelist", "whitelist.txt")
}

// CorePath is the plugin's core.cfg location.
func (w *Whitelist) CorePath() string {
	return filepath.Join(w.cfg.CFGDir(), "cs2whitelist", "core.cfg")
}

// Apply normalizes, dedupes and writes the whitelist file atomically.
// Enabling/disabling enforcement is exposed separately via SetEnabled.
//
// Clearing the list while enforcement is on is refused for the same reason
// SetEnabled refuses to enforce an empty list: the plugin would reject every
// connection, and the operator's only way back would be editing files over SSH.
func (w *Whitelist) Apply(entries []string) ([]string, error) {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		id, err := cs2.NormalizeSteamID(e)
		if err != nil {
			return nil, fmt.Errorf("whitelist: %q: %w", e, err)
		}
		if _, dup := seen[id]; dup {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	sort.Strings(out)

	if len(out) == 0 {
		on, err := w.Enabled()
		if err != nil {
			return nil, err
		}
		if on {
			return nil, fmt.Errorf("whitelist: refusing to clear the list while enforcement is on — that would reject every player, including you; switch enforcement off first")
		}
	}

	var b strings.Builder
	b.WriteString("// cs2a managed whitelist (one SteamID64 per line)\n")
	b.WriteString("// generated by cs2a agent — do not edit while the panel manages it\n")
	for _, id := range out {
		b.WriteString(id + "\n")
	}
	if err := os.MkdirAll(filepath.Dir(w.Path()), 0o755); err != nil {
		return nil, err
	}
	if err := atomicWrite(w.Path(), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}
	return out, nil
}

// Read parses the current whitelist file (ids only, comments skipped).
func (w *Whitelist) Read() ([]string, error) {
	raw, err := os.ReadFile(w.Path())
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		// the plugin treats ; // and # as comment markers
		if line == "" || strings.HasPrefix(line, "#") ||
			strings.HasPrefix(line, "//") || strings.HasPrefix(line, ";") {
			continue
		}
		out = append(out, line)
	}
	return out, nil
}

// reEnableKV matches the "Enable" KeyValues line in core.cfg.
var reEnableKV = regexp.MustCompile(`(?mi)^(\s*")Enable("\s*")[01]("\s*)$`)

// Enabled reports whether the plugin's core.cfg has enforcement switched on.
// A missing config means the plugin is not installed yet (false).
func (w *Whitelist) Enabled() (bool, error) {
	raw, err := os.ReadFile(w.CorePath())
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	m := reEnableKV.FindStringSubmatch(string(raw))
	if m == nil {
		return false, nil
	}
	return strings.Contains(m[0], `"1"`), nil
}

// SetEnabled flips the plugin's "Enable" key in core.cfg, preserving every
// other setting and comment.
//
// core.cfg is only read when the plugin loads, so the file change alone does
// not affect the running server: callers pair this with the plugin's
// `mm_whitelist_enable` cvar over RCON (see API.handlePutWhitelistEnabled).
//
// Enforcing an empty list is refused. The plugin rejects every connection that
// is not on the list, so an empty enforced whitelist takes the server offline
// for everyone — including the operator who flipped the switch, who then has no
// way back in except editing files over SSH. There is no legitimate use for it:
// stopping the server is the supported way to close it.
func (w *Whitelist) SetEnabled(on bool) error {
	if on {
		ids, err := w.Read()
		if err != nil {
			return err
		}
		if len(ids) == 0 {
			return fmt.Errorf("whitelist: refusing to enforce an empty whitelist — it would reject every player, including you; add at least one SteamID first")
		}
	}
	val := "0"
	if on {
		val = "1"
	}
	raw, err := os.ReadFile(w.CorePath())
	if os.IsNotExist(err) {
		if err := os.MkdirAll(filepath.Dir(w.CorePath()), 0o755); err != nil {
			return err
		}
		return atomicWrite(w.CorePath(), []byte(defaultWhitelistCoreCFG(val)), 0o644)
	}
	if err != nil {
		return err
	}
	content := string(raw)
	if !reEnableKV.MatchString(content) {
		return fmt.Errorf("whitelist: no \"Enable\" key found in %s — edit it manually", w.CorePath())
	}
	out := reEnableKV.ReplaceAllString(content, `${1}Enable${2}`+val+`${3}`)
	return atomicWrite(w.CorePath(), []byte(out), 0o644)
}

// writeWhitelistCoreCFG is the post-install step: it creates core.cfg pointing
// at the file cs2a manages, without clobbering an operator's existing config.
//
// Enforcement starts OFF. Installing the plugin used to write Enable "1" while
// whitelist.txt did not exist yet, so the moment the server restarted every
// connection was rejected — the operator had installed a plugin and locked
// themselves out of their own server in one click. Turning it on is a deliberate
// action on the Access page, which requires at least one SteamID.
func writeWhitelistCoreCFG(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil // keep the plugin's or the operator's config
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return atomicWrite(path, []byte(defaultWhitelistCoreCFG("0")), 0o644)
}

// defaultWhitelistCoreCFG is a minimal core.cfg in the plugin's KeyValues
// format. Only the keys cs2a depends on are written; the plugin defaults the
// rest.
func defaultWhitelistCoreCFG(enable string) string {
	return `// managed by cs2a — the panel's Access page flips "Enable"
"cs2whitelist"
{
	"Config"
	{
		// 1 = only whitelisted players may connect, 0 = everyone may
		"Enable"	"` + enable + `"

		// whitelist file, relative to cfg/cs2whitelist/ (cs2a writes it)
		"Filename"	"whitelist.txt"

		// admins with a cs2admin flag bypass the check
		"Immunity"	"1"
	}
}
`
}

// quietExec is the part of *Server the whitelist needs: a fire-and-forget RCON
// command. Kept as an interface so the whitelist tests do not need a live
// server, and so a nil controller is simply a no-op.
type quietExec interface {
	ExecQuiet(command string) error
}

// PushLive mirrors the enforcement switch onto the running server.
//
// The plugin reads core.cfg once, when Metamod finishes loading plugins, and
// copies "Enable" into its mm_whitelist_enable cvar. Flipping the file alone
// therefore had no effect until the next server restart: the panel reported
// success while the server kept enforcing the old value. Setting the cvar is
// what makes the toggle immediate.
//
// Best-effort by design: RCON may be down, and the command simply does not
// exist when the plugin is not installed.
func (w *Whitelist) PushLive(exec quietExec, on bool) {
	if exec == nil {
		return
	}
	val := "0"
	if on {
		val = "1"
	}
	_ = exec.ExecQuiet("mm_whitelist_enable " + val)
	// Turning enforcement on mid-map must not be undone by decisions the plugin
	// already cached, and turning it off should let a rejected player back in
	// without waiting for a map change.
	_ = exec.ExecQuiet("mm_whitelist_cache_clear")
}

// ReloadLive asks the plugin to re-read the whitelist file and forget the
// decisions it cached for this map.
//
// The plugin keeps the parsed list in memory (reloaded on map change) plus a
// per-map cache of who it already allowed or rejected. Adding a player and only
// reloading the file still left them in the rejection cache until the map
// changed, so an operator who fixed a typo saw no effect. The command names come
// from the plugin's own console commands (mm_whitelist_*); the "wl_reload" cs2a
// used to send never existed in any released version.
func (w *Whitelist) ReloadLive(exec quietExec) {
	if exec == nil {
		return
	}
	_ = exec.ExecQuiet("mm_whitelist_reload")
	_ = exec.ExecQuiet("mm_whitelist_cache_clear")
}
