package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"cs2a/internal/cs2"
)

// Whitelist manages the mm-cs2whitelist plugin's data files:
//
//	cfg/cs2whitelist/whitelist.txt  — one normalized SteamID64 per line
//	cfg/cs2whitelist/core.cfg       — KeyValues config with the on/off switch
//
// The plugin has no console variable to toggle enforcement (an earlier version
// of cs2a assumed an "mm_whitelist_enable" cvar, which does not exist): the
// switch lives in core.cfg's "Enable" key and is read on plugin load and each
// map change. cs2a is the single writer of both files.
type Whitelist struct {
	cfg Config
}

// NewWhitelist builds the whitelist service.
func NewWhitelist(cfg Config) *Whitelist { return &Whitelist{cfg: cfg} }

// Path is the whitelist file location.
func (w *Whitelist) Path() string {
	return filepath.Join(w.cfg.CFGDir(), "cs2whitelist", "whitelist.txt")
}

// CorePath is the plugin's core.cfg location.
func (w *Whitelist) CorePath() string {
	return filepath.Join(w.cfg.CFGDir(), "cs2whitelist", "core.cfg")
}

// Apply normalizes, dedupes and writes the whitelist file atomically.
// Enabling/disabling enforcement is exposed separately via SetEnabled.
func (w *Whitelist) Apply(entries []string) ([]string, error) {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		id, err := cs2.NormalizeSteamID(e)
		if err != nil {
			return nil, fmt.Errorf("whitelist: %q: %w", e, err)
		}
		if _, dup := seen[id]; dup {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	sort.Strings(out)

	var b strings.Builder
	b.WriteString("// cs2a managed whitelist (one SteamID64 per line)\n")
	b.WriteString("// generated by cs2a agent — do not edit while the panel manages it\n")
	for _, id := range out {
		b.WriteString(id + "\n")
	}
	if err := os.MkdirAll(filepath.Dir(w.Path()), 0o755); err != nil {
		return nil, err
	}
	if err := atomicWrite(w.Path(), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}
	return out, nil
}

// Read parses the current whitelist file (ids only, comments skipped).
func (w *Whitelist) Read() ([]string, error) {
	raw, err := os.ReadFile(w.Path())
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		// the plugin treats ; // and # as comment markers
		if line == "" || strings.HasPrefix(line, "#") ||
			strings.HasPrefix(line, "//") || strings.HasPrefix(line, ";") {
			continue
		}
		out = append(out, line)
	}
	return out, nil
}

// reEnableKV matches the "Enable" KeyValues line in core.cfg.
var reEnableKV = regexp.MustCompile(`(?mi)^(\s*")Enable("\s*")[01]("\s*)$`)

// Enabled reports whether the plugin's core.cfg has enforcement switched on.
// A missing config means the plugin is not installed yet (false).
func (w *Whitelist) Enabled() (bool, error) {
	raw, err := os.ReadFile(w.CorePath())
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	m := reEnableKV.FindStringSubmatch(string(raw))
	if m == nil {
		return false, nil
	}
	return strings.Contains(m[0], `"1"`), nil
}

// SetEnabled flips the plugin's "Enable" key in core.cfg, preserving every
// other setting and comment. The plugin re-reads it on the next map change;
// callers may also issue its `wl_reload` command over RCON for an instant
// effect.
func (w *Whitelist) SetEnabled(on bool) error {
	val := "0"
	if on {
		val = "1"
	}
	raw, err := os.ReadFile(w.CorePath())
	if os.IsNotExist(err) {
		if err := os.MkdirAll(filepath.Dir(w.CorePath()), 0o755); err != nil {
			return err
		}
		return atomicWrite(w.CorePath(), []byte(defaultWhitelistCoreCFG(val)), 0o644)
	}
	if err != nil {
		return err
	}
	content := string(raw)
	if !reEnableKV.MatchString(content) {
		return fmt.Errorf("whitelist: no \"Enable\" key found in %s — edit it manually", w.CorePath())
	}
	out := reEnableKV.ReplaceAllString(content, `${1}Enable${2}`+val+`${3}`)
	return atomicWrite(w.CorePath(), []byte(out), 0o644)
}

// writeWhitelistCoreCFG is the post-install step: it creates core.cfg pointing
// at the file cs2a manages, without clobbering an operator's existing config.
func writeWhitelistCoreCFG(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil // keep the plugin's or the operator's config
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return atomicWrite(path, []byte(defaultWhitelistCoreCFG("1")), 0o644)
}

// defaultWhitelistCoreCFG is a minimal core.cfg in the plugin's KeyValues
// format. Only the keys cs2a depends on are written; the plugin defaults the
// rest.
func defaultWhitelistCoreCFG(enable string) string {
	return `// managed by cs2a — the panel's Access page flips "Enable"
"cs2whitelist"
{
	"Config"
	{
		// 1 = only whitelisted players may connect, 0 = everyone may
		"Enable"	"` + enable + `"

		// whitelist file, relative to cfg/cs2whitelist/ (cs2a writes it)
		"Filename"	"whitelist.txt"

		// admins with a cs2admin flag bypass the check
		"Immunity"	"1"
	}
}
`
}
